services:
  minecraft:
    image: dockerhub.timeweb.cloud/itzg/minecraft-server:latest
    container_name: mc-server
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.21.11"
      SEED: "2048005618087379093"
      MEMORY: "4G"           
      INIT_MEMORY: "2G"
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled" 
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft:/data
    restart: unless-stopped
    depends_on:
      - mc-db

  mc-db:
    image: dockerhub.timeweb.cloud/library/postgres:16-alpine
    container_name: mc-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mc_admin
      POSTGRES_PASSWORD: super_secret_password_123
      POSTGRES_DB: minecraft_data
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db_data: